# Generated by Django 2.2.8 on 2020-02-04 17:53

from django.db import migrations, models
import imagekit.models.fields
import videos.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_videopageindex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videopage',
            old_name='url',
            new_name='url_address',
        ),
        migrations.AlterField(
            model_name='videopage',
            name='banner',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=videos.models.gen_file_name),
        ),
        migrations.AlterField(
            model_name='videopage',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='videopage',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
