# Generated by Django 2.2.8 on 2020-03-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_videopage_ctag'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopage',
            name='uuid',
            field=models.CharField(default='', max_length=50, verbose_name='UUID'),
        ),
    ]
