# Generated by Django 2.2.8 on 2020-02-23 08:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete='models.CASCADE', related_name='uprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
