# Generated by Django 2.2.8 on 2020-03-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200225_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.CharField(default='', max_length=300, verbose_name='Company'),
            preserve_default=False,
        ),
    ]
