# Generated by Django 2.2.8 on 2020-02-03 01:00

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('location', models.TextField()),
                ('lat', models.DecimalField(decimal_places=16, default='0.00', max_digits=22, verbose_name='Lat')),
                ('lng', models.DecimalField(decimal_places=16, default='0.00', max_digits=22, verbose_name='Lng')),
                ('body', wagtail.core.fields.StreamField([('details', wagtail.core.blocks.StructBlock([('details', wagtail.core.blocks.RichTextBlock())]))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EventPageIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
