# Generated by Django 2.2.8 on 2020-02-06 06:51

from django.db import migrations, models
import django.db.models.deletion
import events.models
import imagekit.models.fields
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_eventpartner'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=events.models.gen_file_name),
        ),
        migrations.CreateModel(
            name='EventPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('event', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_partner', to='events.Event')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partners.EventPartner')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
