# Generated by Django 2.2.8 on 2020-02-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200211_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bm_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='BM ID'),
        ),
        migrations.AddField(
            model_name='event',
            name='etype',
            field=models.CharField(choices=[('physical', 'Physical'), ('webinar', 'Webinar')], default='physical', max_length=50, verbose_name='Event Type'),
        ),
    ]
