# Generated by Django 2.2.8 on 2020-03-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200224_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reg_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
