# Generated by Django 2.2.8 on 2020-02-06 06:51

from django.db import migrations, models
import imagekit.models.fields
import partners.models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=partners.models.gen_file_name)),
                ('name', models.CharField(max_length=50, verbose_name='Partner')),
            ],
        ),
    ]
