# Generated by Django 2.2.8 on 2020-02-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_eventpartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='row',
            field=models.IntegerField(default=0),
        ),
    ]
