# Generated by Django 2.2.8 on 2021-02-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_partner_ptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='ptype',
            field=models.CharField(choices=[('fixed', 'fixed'), ('self-serve', 'self-serve')], default='fixed', max_length=50, verbose_name='Partner Type'),
        ),
    ]
