# Generated by Django 2.2.8 on 2020-01-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20190627_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='uuid',
            field=models.CharField(default='', max_length=50, verbose_name='UUID'),
            preserve_default=False,
        ),
    ]
