# Generated by Django 2.2.8 on 2020-02-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='subjects',
            field=models.ManyToManyField(to='forum.Subject'),
        ),
    ]
