# Generated by Django 2.2.8 on 2020-03-16 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='courses',
            new_name='course',
        ),
    ]
