# Generated by Django 2.2.8 on 2020-04-07 01:08

import attendances.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendances', '0004_auto_20200403_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=attendances.models.gen_file_name)),
                ('name', models.CharField(max_length=200, verbose_name='Badge Name')),
            ],
        ),
        migrations.CreateModel(
            name='SpecAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendances.SpecBadge')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
