# Generated by Django 2.2.8 on 2020-02-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsresources',
            name='type',
            field=models.CharField(choices=[('regulators', 'Regulators'), ('tools', 'Tools'), ('partners', 'Partners')], default='tools', max_length=100),
        ),
    ]
