# Generated by Django 2.2.8 on 2020-03-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_resources', '0002_toolsresources_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsresources',
            name='type',
            field=models.CharField(choices=[('regulators', 'Regulators'), ('tools', 'Tools'), ('partners', 'Partners'), ('learning', 'Learning Bodies')], default='tools', max_length=100),
        ),
    ]
