# Generated by Django 2.2.8 on 2020-04-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_resources', '0003_auto_20200319_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsresources',
            name='type',
            field=models.CharField(choices=[('regulators', 'Regulators'), ('tools', 'Tools'), ('partners', 'Channel Partners'), ('learning', 'Accreditation Partners')], default='tools', max_length=100),
        ),
    ]
