# Generated by Django 2.2.8 on 2020-02-09 10:33

import blog.abstract
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200105_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='header_image',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='banner',
            field=models.ImageField(default='', upload_to=blog.abstract.gen_file_name),
            preserve_default=False,
        ),
    ]
