# Generated by Django 2.2.8 on 2020-03-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpage_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
