# Generated by Django 2.2.8 on 2020-02-01 21:50

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200201_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='course',
            name='email',
        ),
        migrations.AlterField(
            model_name='course',
            name='body',
            field=wagtail.core.fields.StreamField([('details', wagtail.core.blocks.StructBlock([('overview', wagtail.core.blocks.RichTextBlock()), ('details', wagtail.core.blocks.RichTextBlock()), ('included', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock(label='Item'))), ('fees', wagtail.core.blocks.RichTextBlock()), ('registration', wagtail.core.blocks.RichTextBlock()), ('ideal_for', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock(label='Item'))), ('contact', wagtail.core.blocks.CharBlock()), ('email', wagtail.core.blocks.CharBlock())]))]),
        ),
    ]
