# Generated by Django 2.2.8 on 2020-02-02 06:09

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200202_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='ctags',
            field=modelcluster.fields.ParentalManyToManyField(to='utils.Tag'),
        ),
    ]
