# Generated by Django 2.2.8 on 2020-02-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='promoted',
            field=models.BooleanField(default=False),
        ),
    ]
