# Generated by Django 2.2.8 on 2020-02-19 15:16

import courses.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_promoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='badge',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=courses.models.gen_file_name),
        ),
    ]
