# Generated by Django 2.2.8 on 2020-03-23 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_testimonials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='testimonials',
        ),
    ]
