# Generated by Django 2.2.8 on 2020-03-27 04:31

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20200324_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='body',
            field=wagtail.core.fields.StreamField([('details', wagtail.core.blocks.StructBlock([('overview', wagtail.core.blocks.RichTextBlock()), ('details', wagtail.core.blocks.RichTextBlock()), ('included', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock(label='Item'))), ('fees', wagtail.core.blocks.RichTextBlock()), ('registration', wagtail.core.blocks.RichTextBlock()), ('ideal_for', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock(label='Item'))), ('contact', wagtail.core.blocks.CharBlock()), ('email', wagtail.core.blocks.CharBlock()), ('testimonials', wagtail.core.blocks.StreamBlock([('testimonials', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(label='Name')), ('text', wagtail.core.blocks.TextBlock(label='Text')), ('title', wagtail.core.blocks.CharBlock(label='Title', required=False))]))], required=False))]))]),
        ),
    ]
