# Generated by Django 2.2.8 on 2020-04-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogcategory_order'),
        ('home', '0004_staticpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSpecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Home Special')),
                ('blog', models.ManyToManyField(to='blog.BlogPage')),
            ],
        ),
    ]
