# Generated by Django 2.2.8 on 2020-02-07 11:27

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import research.models
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('name', models.CharField(max_length=100)),
                ('description', wagtail.core.fields.RichTextField()),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('pdf', models.FileField(upload_to=research.models.gen_file_name)),
                ('banner', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=research.models.gen_banner_name)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ResearchPageIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
