# Generated by Django 2.2.8 on 2020-01-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_conversation', '0011_remove_post_poster_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='uuid',
            field=models.CharField(default='', max_length=50, verbose_name='UUID'),
            preserve_default=False,
        ),
    ]
