# Generated by Django 2.2.8 on 2020-02-13 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_conversation', '0013_topic_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='subjects',
            new_name='tags',
        ),
    ]
