# Generated by Django 2.2.8 on 2021-02-01 14:08

import django.contrib.postgres.fields
from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_auto_20200316_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, verbose_name='Key')),
                ('val', models.TextField(blank=True, null=True)),
                ('ftype', models.CharField(default='text', max_length=50, verbose_name='Ftype')),
                ('val_file', models.ImageField(blank=True, null=True, upload_to=utils.models.gen_file_name)),
                ('val_arr', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
            ],
        ),
    ]
