# Generated by Django 2.2.8 on 2020-03-23 00:57

import advisors.models
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=advisors.models.gen_file_name)),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('description', models.TextField()),
            ],
        ),
    ]
