# Generated by Django 2.2.8 on 2020-03-23 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisorprofile',
            old_name='banner',
            new_name='image',
        ),
    ]
