# Generated by Django 2.2.8 on 2020-03-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0002_auto_20200323_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorprofile',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
